version: '3'

services:
  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
#    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    command: gunicorn task_manager.wsgi:application --bind 0.0.0.0:8000
    command: [ "./wait-for-it.sh", "db:5432", "--",
               "python", "/app/task_manager/manage.py", "runserver",
               "0.0.0.0:8000" ]
    restart: always
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=task_manager.settings.prod
      - POSTGRES_USER = ${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD = ${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB = ${POSTGRES_DB_NAME}
    depends_on:
      - db



volumes:
  postgres_data: